service: car-wash
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - lambda:InvokeFunction
            - sns:Publish
            - sns:SetSMSAttributes
            - "s3:*"
          Resource:
            - arn:aws:dynamodb:us-east-1:*:*
            - arn:aws:lambda:us-east-1:*:*
            - "*"
            - arn:aws:s3:::${self:provider.environment.IMAGE_BUCKET}/*
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: secretkey
    USER_TABLE: users
    IMAGE_BUCKET: car-wash-uploads
    WASH_PACKAGE_TABLE: wash-packages
    BOOKING_TABLE: bookings
functions:
  customerSignup:
    handler: handlers/user.signup
    events:
      - http:
          path: customer/signup
          method: POST
          cors: true
  washerSignup:
    handler: handlers/user.signup
    events:
      - http:
          path: washer/signup
          method: POST
          cors: true
  login:
    handler: handlers/user.login
    events:
      - http:
          path: user/login
          method: POST
  authorize:
    handler: handlers/authorize.handler
  updateProfile:
    handler: handlers/user.updateProfile
    events:
      - http:
          path: profile
          method: POST
          authorizer: authorize
          cors: true
  addCars:
    handler: handlers/car.addCar
    events:
      - http:
          path: car
          method: POST
          authorizer: authorize
          cors: true
  listCars:
    handler: handlers/car.listCar
    events:
      - http:
          path: cars
          method: GET
          cors: true
          authorizer: authorize
  sendSms:
    handler: handlers/helper.sendSms
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
  imageUpload:
    handler: handlers/helper.imageUpload
    events:
      - http:
          path: upload/{folder}
          method: POST
          cors: true
  addWashPackage:
    handler: handlers/washPackage.add
    events:
      - http:
          path: wash-package
          method: POST
          cors: true
          authorizer: authorize
  listWashPackage:
    handler: handlers/washPackage.listPackages
    events:
      - http:
          path: wash-package
          method: GET
          authorizer: authorize
  bookWashing:
    handler: handlers/booking.bookWash
    events:
      - http:
          path: wash-booking
          method: POST
          authorizer: authorize
          cors: true
resources:
  Resources:
    TodosTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users'
    authTokensTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          - 
            AttributeName: token
            AttributeType: S
        KeySchema:
          -
            AttributeName: token
            KeyType: HASH
          -
            AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'auth-tokens'
    userCarsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: plateNumber
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: plateNumber
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'user-cars'
    washPackagesTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'wash-packages'
    bookingsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: packageId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: packageId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'bookings'